# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CXuKM6t3F4fF-oVrTHeQXfFs6n6SKqeR
"""

from random import choices, randint, randrange, random
from typing import List, Optional, Callable, Tuple
from collections import namedtuple
from functools import partial


Genome = List[int]
Population = List[Genome]
PopulateFunc = Callable[[], Population]

FitnessFunc = Callable[[Genome], int]
SelectionFunc = Callable[[Population, FitnessFunc], Tuple[Genome, Genome]]
CrossoverFunc = Callable[[Genome, Genome], Tuple[Genome, Genome]]
MutationFunc = Callable[[Genome], Genome]
PrinterFunc = Callable[[Population, int, FitnessFunc], None]

Thing = namedtuple('Thing', ['name', 'value', 'weight'])

"Thing= 'name', 'value', 'weight']" 

things = [
    Thing('item1', 5, 7),
    Thing('item2', 8, 8),
    Thing('item3', 3, 4),
    Thing('item4', 2, 10),
    Thing('item5', 7, 4),
    Thing('item6', 9, 6),
    Thing('item7', 4, 4)
  
]



"genetic representation of solution  "
def generate_genome(length: int) -> Genome:
    return choices([0, 1], k=length)

"generate a population "
def generate_population(size: int, genome_length: int) -> Population:
    return [generate_genome(genome_length) for _ in range(size)]    


def fitness(genome: Genome, things,  weight_limit: int) -> int:
    if len(genome) != len(things):
        raise ValueError("genome and things must be of same length")

    weight = 0
    value = 0
    for i, thing in enumerate(things):
        if genome[i] == 1:
            weight += thing.weight
            value += thing.value

            if weight > weight_limit:
                return 0

    return value



def selection_pair(population: Population, fitness_func: FitnessFunc) -> Population:
    return choices(
        population=population,
        weights=[fitness_func(gene) for gene in population],
        k=2
    )



def single_point_crossover(a: Genome, b: Genome) -> Tuple[Genome, Genome]:
    if len(a) != len(b):
        raise ValueError("Genomes a and b must be of same length")

    length = len(a)
    if length < 2:
        return a, b

    p = randint(1, length - 1)
    return a[0:p] + b[p:], b[0:p] + a[p:]



def mutation(genome: Genome, num: int = 1, probability: float = 0.5) -> Genome:
    for _ in range(num):
        index = randrange(len(genome))
        genome[index] = genome[index] if random() > probability else abs(genome[index] - 1)
    return genome





def run_evolution(
        populate_func: PopulateFunc,
        fitness_func: FitnessFunc,
        fitness_limit: int,
        selection_func: SelectionFunc = selection_pair,
        crossover_func: CrossoverFunc = single_point_crossover,
        mutation_func: MutationFunc = mutation,
        generation_limit: int = 100,
        printer: Optional[PrinterFunc] = None) \
        -> Tuple[Population, int]:
    population = populate_func()

    for i in range(generation_limit):
        population = sorted(population, key=lambda genome: fitness_func(genome), reverse=True)

        if printer is not None:
            printer(population, i, fitness_func)

        if fitness_func(population[0]) >= fitness_limit:
            break

        next_generation = population[0:2]

        for j in range(int(len(population) / 2) - 1):
            parents = selection_func(population, fitness_func)
            offspring_a, offspring_b = crossover_func(parents[0], parents[1])
            offspring_a = mutation_func(offspring_a)
            offspring_b = mutation_func(offspring_b)
            next_generation += [offspring_a, offspring_b]

        population = next_generation

    return population, i

Population , generations = run_evolution (
    populate_func=partial(
        generate_population, size = 10 , genome_length=len(things)
    ),
    fitness_func=partial(
        fitness , things=things , weight_limit=22
    ),

    fitness_limit=100, 
   generation_limit= 100

)


def genome_to_things(genome : Genome , things) -> things :

 result = [] 
 for i , things in enumerate(things) : 
    if genome[i] == 1 :
      result += [things.name]

 return result


print(f"number of  generations :{generations}")
 
print(f"best solution :{genome_to_things(Population[0],things)} ")